const ERROR = {
    // common
    COMMON_FORBIDDEN: "COMMON_FORBIDDEN",
    COMMON_SERVER_INTERNAL_ERROR: "COMMON_SERVER_INTERNAL_ERROR",
    COMMON_NOT_FOUND: "COMMON_NOT_FOUND",
    COMMON_GONE: "COMMON_GONE",
    COMMON_BAD_REQUEST: "COMMON_BAD_REQUEST",
    COMMON_CONFLICT: "COMMON_CONFLICT",
    COMMON_TIMEOUT_ERROR: "COMMON_TIMEOUT_ERROR",
    COMMON_UNAUTHORIZED: "COMMON_UNAUTHORIZED",

    // account
    FIELD_NAME_NOT_FOUND: "FIELD_NAME_NOT_FOUND",
    IDENTITY_DUPLICATE_EMAIL: "IDENTITY_DUPLICATE_EMAIL",
    NUMBER_OF_QUESTION_EXCEED_LIMIT: "NUMBER_OF_QUESTION_EXCEED_LIMIT",
    ACCOUNT_NOTFOUND: "ACCOUNT_NOTFOUND",
    ACCOUNT_LOCKED: "ACCOUNT_LOCKED",
    ACCOUNT_BANNED: "ACCOUNT_BANNED",
    ACCOUNT_EMAIL_BANNED: "ACCOUNT_EMAIL_BANNED",
    ACCOUNT_EMAIL_NOT_VERIFIED: "ACCOUNT_EMAIL_NOT_VERIFIED",
    ACCOUNT_USERNAME_ALREADY_EXISTS: "ACCOUNT_USERNAME_ALREADY_EXISTS",
    ACCOUNT_EMAIL_ALREADY_EXISTS: "ACCOUNT_EMAIL_ALREADY_EXISTS",
    ACCOUNT_INVALID_PASSWORD: "ACCOUNT_INVALID_PASSWORD",
    ACCOUNT_INVALID_CREDENTIALS: "ACCOUNT_INVALID_CREDENTIALS",
    ACCOUNT_INVALID_RESET_CODE: "ACCOUNT_INVALID_RESET_CODE",
    ACCOUNT_INVALID_VERIFICATION_CODE: "ACCOUNT_INVALID_VERIFICATION_CODE",
    ACCOUNT_LOCKED_OUT: "ACCOUNT_LOCKED_OUT",
    ACCOUNT_WRONG_PASSWORD: "ACCOUNT_WRONG_PASSWORD",
    EMAIL_VERIFICATION_CODE_FAILED_TOO_MANY: "EMAIL_VERIFICATION_CODE_FAILED_TOO_MANY",
    EMAIL_VERIFICATION_REQUEST_TOO_MANY: "EMAIL_VERIFICATION_REQUEST_TOO_MANY",
    PASSWORD_RESET_CODE_FAILED_TOO_MANY: "PASSWORD_RESET_CODE_FAILED_TOO_MANY",
    PASSWORD_RESET_REQUEST_TOO_MANY: "PASSWORD_RESET_REQUEST_TOO_MANY",

    // class
    CLASS_NOTFOUND: "CLASS_NOTFOUND",
    CLASS_ALREADY_EXISTS: "CLASS_ALREADY_EXISTS",
    CLASS_CODE_NOT_FOUND: "CLASS_CODE_NOT_FOUND",
    ONLY_OWNERS_CAN_UPDATE: "ONLY_OWNERS_CAN_UPDATE",
    STUDENT_ALREADY_EXISTS_IN_CLASS: "STUDENT_ALREADY_EXISTS_IN_CLASS",
    NOT_FOUND_STUDENT: "NOT_FOUND_STUDENT",
    NOT_FOUND_STUDENT_IN_CLASS: "NOT_FOUND_STUDENT_IN_CLASS", //may be the same with the one below
    NOT_FOUND_USER_IN_CLASS: "NOT_FOUND_USER_IN_CLASS",
    STUDENT_CAN_REVIEW_THIS_TEST: "STUDENT_CAN_REVIEW_THIS_TEST",

    // question set
    QUESTION_SET_ALREADY_IN_CLASS: "QUESTION_SET_ALREADY_IN_CLASS",
    QUESTION_SET_NOT_FOUND: "QUESTION_SET_NOT_FOUND",
    QUESTION_SET_NOT_FOUND_IN_CLASS: "QUESTION_SET_NOT_FOUND_IN_CLASS",

    //plan
    PLAN_REQUIRE_PLAN: "PLAN_REQUIRE_PLAN",
    INSUFFICIENT_BALANCE: "INSUFFICIENT_BALANCE",

    //test
    TEST_IS_OVERDUE: "TEST_IS_OVERDUE",
    MAX_ATTEMPT_IN_THIS_TEST: "MAX_ATTEMPT_IN_THIS_TEST",

    //folder
    TEST_TEMPLATE_ALREADY_EXISTS_IN_FOLDER: "TEST_TEMPLATE_ALREADY_EXISTS_IN_FOLDER",

    //test template
    USER_NOT_HAVE_PERMISSION_IN_TEST_TEMPLATE: "USER_NOT_HAVE_PERMISSION_IN_TEST_TEMPLATE",

    //file
    FILE_EMPTY: "FILE_EMPTY",
    FILE_TOO_LARGE: "FILE_TOO_LARGE",
    PDF_PAGE_LIMIT_EXCEEDED: "PDF_PAGE_LIMIT_EXCEEDED",
    INVALID_FILE_TYPE: "INVALID_FILE_TYPE",
};

export default ERROR;
